# Generated by Django 3.1.7 on 2024-05-19 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210707_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='show',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.show'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='api.role'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='api.show'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
