# Generated by Django 3.1.7 on 2024-05-19 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240519_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='role', to='api.role'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='show', to='api.show'),
        ),
        migrations.AlterField(
            model_name='role',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.show'),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
